  services:
    webadmin:
      image: tranngoctu512004/webadmin:latest
      build: .
      container_name: webadmin
      restart: always
      ports:
        - '4001:4001'
      volumes:
        - ./.env:/app/.env        
        